engine/urls.py
from django.contrib import admin
#from django.urls import include, path
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls import handler404, handler500

from django.conf import settings as django_settings
from django.conf.urls.static import static
from .sitemap import urls as sitemap_urls

from . import views
app_name = 'engine'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^teams/$', views.teams, name='teams'),
    url(r'^matches/$', views.matches, name='matches'),
    url(r'^arenas/$', views.arenas, name='arenas'),
    url(r'^champs/$', views.champs, name='champs'),
    url(r'^news/$', views.news, name='news'),
    url(r'^ajax/$', views.ajax, name='ajax'),
    url(r'^parse/$', views.parse, name='parse'),
    url(r'^auto-news/$', views.auto_news, name='auto-news'),
    url(r'^feed.xml/$', views.feed_xml, name='feed_xml'),
    url(r'^sendsay_push_sw.js$', views.sendsay_jsfile, name='feed_xml'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^clear_all_cache/$', views.clear_all_cache_view, name='clear_all_cache_view'),
    url(r'^order_success/$', views.order_success, name='order_success'),
    url(r'^get_missing_orders/$', views.get_missing_orders, name='get_missing_orders'),
    url(r'^check_reserve_orders/$', views.check_reserve_orders, name='check_reserve_orders'),
    url(r'^certificates/$', views.certificates, name='certificates'),
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^get_content_plan/$', views.get_content_plan, name='get_content_plan'),
    url(r'^control_panel/$', views.control_panel, name='control_panel'),
    url(r'^orders_check/$', views.orders_check, name='orders_check'),
    url(r'^teams/(?P<alias>[0-9A-Za-z\-]+)/$', views.team, name='team'),
    url(r'^news/(?P<alias>[0-9A-Za-z\-]+)/$', views.news_item, name='news_item'),
    url(r'^champs/(?P<alias>[0-9A-Za-z\-_]+)/$', views.champ, name='champ'),
    url(r'^arenas/(?P<alias>[0-9A-Za-z\-_]+)/$', views.arena, name='arena'),
    url(r'^matches/(?P<alias>[0-9A-Za-z\-_]+)/$', views.match_preview, name='match_preview'),
    url(r'^matches/(?P<static_url>[0-9A-Za-z\-_]+)/(?P<match_url>[0-9A-Za-z\-_]+)/$', views.match, name='match'),
    url(r'^create_double/(?P<alias>[0-9]+)/$', views.create_double, name='create_double'),
    url(r'^(?P<alias>[0-9A-Za-z\-]+)/$', views.textpage, name='textpage'),
] + sitemap_urls + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

footballengine/urls.py
from django.contrib import admin
#from django.urls import include, path
from rest_framework import routers
from . import routers
from django.conf.urls import url, include
from django.conf import settings as django_settings
from django.conf.urls.static import static
from acquiring_client import urls as acq_urls

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^api/', include(routers.router.urls)),
    url(r'^', include('engine.urls', namespace="main")),
    url(r'^payment/', include(acq_urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(django_settings.MEDIA_URL, document_root=django_settings.MEDIA_ROOT)

templates/_match-item-matches.html
{% load i18n %}
<div class="championat__element matches_el" data-team-1="{{ m.command_first.id }}" data-team-2="{{ m.command_second.id }}" champ_id="{{ m.champ.id }}" data-match_name="{{ m.name }}" data-datetime="{{ m.datetime|date:'Y-m-d H:i' }}">
    <div class="matches_el__left">
        <div class="matches_el__img">
            <img src="{% if m.command_first.logo2 %}{{ m.command_first.logo2.url }}{% endif %}" alt="" width="56px">
        </div>
        <div class="matches_el__img">
            <img src="{% if m.command_second.logo2 %}{{ m.command_second.logo2.url }}{% endif %}" alt="" width="56px">
        </div>
    </div>
    <div class="matches_el__right">
        <div class="matches_el__main">
            <div class="matches_el__title">
                <a href="{% url 'engine:team' m.command_first.alias %}">{{ m.command_first.name }}</a>
                <span>{% if not m.score %}vs{% else %}{{ m.score }}{% endif %}</span>
                <a href="{% url 'engine:team' m.command_second.alias %}">{{ m.command_second.name }}</a>
            </div>
            <div class="matches_el__date">{% if m.datetime_tz %}{{ m.datetime_tz|date:"j F, l, H:i" }}{% else %}{{ m.datetime|date:"j F, l, H:i" }}{% endif %}</div>
            <div class="matches_el__loсation">
                {% if m.stadium.city.name or m.stadium.name %}
                    {{ m.stadium.city.name }}, <a href="{% url 'engine:arena' m.stadium.alias %}">{{ m.stadium.name }}</a>
                {% endif %}
            </div>
            <div class="matches_el__bottom">
                {% if m.carryall_id or m.static_tickets.all|length %}
                    <a href="{% url 'engine:match' m.static_match.alias m.alias %}" class="matches_el__link">
                        {% trans "Выбрать билеты" %}
                    </a>
                {% else %}
                    {% if m.hide_match %}
                        <a href="javascript:" class="matches_el__link" style="opacity: 0;">
                            {% trans "Оставить заявку" %}
                        </a>
                    {% else %}
                        <a href="javascript:" class="matches_el__link championat__button-request">
                            {% trans "Оставить заявку" %}
                        </a>
                    {% endif %}
                {% endif %}
                <a href="{% url 'engine:match_preview' m.static_match.alias %}" class="matches_el__more">{% trans "Подробно о матче" %}</a>
            </div>
        </div>
        {% if m.champ.image %}
            <div class="matches_el__league" style="background-image: url({{ m.champ.image.url }});"></div>
        {% endif %}
    </div>
</div>

templates/_match-list-item.html
<div href="javascript:" class="championat__element" data-team-1="{{ m.command_first.id }}" data-team-2="{{ m.command_second.id }}" champ_id="{{ m.champ.id }}" data-match_name="{{ m.name }}" data-datetime="{{ m.datetime|date:'Y-m-d H:i' }}">
    <div class="championat__right" style="width: 100%; padding-left: 0;">
        <div class="championat__top">
            <div class="championat__team">
                <div class="championat__image {% if m.command_first.id == 226 %}{{ m.id }}{% endif %}" style="background: url(/media/teams/{{ m.command_first.logo }}) center no-repeat; background-size: contain;">
                    <img src="https://footballengine.tix-system.com/media/teams/{{ m.command_first.logo }}" width="56px">
                </div>
                <div class="championat__name">{{ m.command_first.name }}</div>
            </div>
            <div class="championat__line"></div>
            <div class="championat__team">
                <div class="championat__name">{{ m.command_second.name }}</div>
                <div class="championat__image {% if m.command_second.id == 226 %}{{ m.id }}{% endif %}" style="background: url(/media/teams/{{ m.command_second.logo }}) center no-repeat; background-size: contain;">
                    <img src="https://footballengine.tix-system.com/media/teams/{{ m.command_second.logo }}" width="56px">
                </div>
            </div>
        </div>
        <div class="championat__bottom" style="display: block;">
            <div class="half_width championat__location" style="font-size: 12px;">
            {% if m.stadium.city.name or m.stadium.name %}
                {{ m.stadium.city.name }}, {{ m.stadium.name }}
            {% else %}
                <div></div>
            {% endif %}
            </div>
            <div class="half_width">
                <a href="{% url 'engine:match_preview' m.static_match.alias %}"><div style="margin-left: 15px; float: right; margin-bottom: 5px;" class="championat__button">Подробнее</div></a>
                {% if m.carryall_id or m.static_tickets.all|length %}<a href="{% url 'engine:match' m.static_match.alias m.alias %}"><div style="margin-left: 15px; float: right;" class="championat__button">{% trans "Выбрать билеты" %}</div></a>{% else %}<div style="margin-left: 15px; float: right;" class="championat__button championat__button-request">{% trans "Оставить заявку" %}</div>{% endif %}
            </div>
        </div>
    </div>
</div>

templates/arena.html
{% extends "_base.html" %}
{% load i18n %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ seo_title.stadium }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ seo_description.stadium }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ seo_keywords.stadium }}{% endif %}">
{% endblock %}

{% block container %}
<div class="team_page minimum">
    <div class="match__head"><span>{% if data.seo_h1 %}{{ data.seo_h1 }}{% else %}{{ data.name }}{% endif %}</span></div>
    <div class="wrapper">
        <div class="breadcrumbs">
            <a href="/">{% trans "Билеты на матчи" %}</a>
            <a href="/arenas/">{% trans "Стадионы" %}</a>
            <span>{{ data.name }}</span>
        </div>
        <h1 class="match__h1">{% if data.seo_h1 %}{{ data.seo_h1 }}{% else %}{{ seo_h1.stadium }}{% endif %}</h1>
    </div>
    <div class="seo_text">
        <div class="wrapper">
            {{ data.content|safe }}
        </div>
    </div>
    <div class="team_grey">
        <div class="wrapper">
            <h2 class="match__h2">{% trans "Все матчи на стадионе" %} {{ data.name }}</h2>
            <div class="championat">
                <div class="championat__wrp">
                    {% for m in stad_matches %}
                        {% include "_match-item-matches.html"%}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/champ.html
{% extends "_base.html" %}
{% load i18n %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ data.name }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ data.name }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ data.name }}{% endif %}">
{% endblock %}

{% block container %}
{% if data.sitesettings.main_champ %}
    <div class="seasons_page minimum">
        <div class="match__head"><span>Сезон {{ data.football_years }}</span></div>
        <div class="wrapper">
            <div class="breadcrumbs">
                <a href="/">{% trans "Билеты на матчи" %}</a>
                <span>Чемпионаты</span>
            </div>
            <h1 class="match__h1">{{ data.name }} - Сезон {{ data.football_years }}</h1>
            <div class="seasons_page__wrp" align="center">
                <h2 style="margin-bottom: 20px;">Команды в чемпионате</h2>
                <div class="team_tms">
                    {% for t in data.teams.all %}
                        <div class="team_bl" style="display: inline-block; width: 6%;">
                            <a href="{% url 'engine:team' t.alias %}"><img src="{% if t.logo2 %}{{ t.logo2.url }}{% endif %}" style="width: 50%; display: inline-block; margin: 0 auto;"></a>
                        </div>
                    {% endfor %}
                </div>
                <h2 style="margin-top: 20px;">Матчи в Чемпионате</h2>
                <div class="match_list">
                {% for m in champ_matches %}
                    {% include "_match-item-matches.html" %}
                {% endfor %}
                </div>
            </div>
            <article class="seo_text">
                {% if data.content %}
                    {% if data.cotnent %}{{ data.content|safe }}{% endif %}
                {% else %}
                    {% if seo_content %}{{ seo_content|safe }}{% endif %}
                {% endif %}
            </article>
        </div>
    </div>
{% else %}
    <div class="seasons_page minimum">
        <div class="match__head"><span>Сезон {{ data.football_years }}</span></div>
        <div class="wrapper">
            <div class="breadcrumbs">
                <a href="/">{% trans "Билеты на матчи" %}</a>
                <span>Чемпионаты</span>
            </div>
            <h1 class="match__h1">{{ data.name }} - Сезон {{ data.football_years }}</h1>
            <div class="seasons_page__wrp" align="center">
                <h2 style="margin-bottom: 20px;">Команды в чемпионате</h2>
                <div class="team_tms">
                    {% for t in data.teams.all %}
                        <div class="team_bl" style="display: inline-block; width: 6%;">
                            <a href="{% url 'engine:team' t.alias %}"><img src="{% if t.logo2 %}{{ t.logo2.url }}{% endif %}" style="width: 50%; display: inline-block; margin: 0 auto;"></a>
                        </div>
                    {% endfor %}
                </div>
                <div class="match_tabs" style="width: 40%; margin: 20px auto 0;">
                    <div class="switch">
                        <div data-id="1" class="switch__element active">
                            Будущие матчи
                        </div>
                        <div data-id="2" class="switch__element">
                            Прошедшие матчи
                        </div>
                    </div>
                </div>
                <div class="match_list map__condition active" data-id="1">
                {% for m in next %}
                    {% include "_match-item-matches.html" %}
                {% endfor %}
                {% if next.has_next or next.has_previous %}
                    <div class="search_nav">
                        <div class="search_nav__help">{{ next.start_index }}—{{ next.end_index }}</div>
                        {% if next.has_previous %}
                        <a href="?next={{ next.previous_page_number }}"><div class="search_nav__next">← назад</div></a>
                        {% endif %}
                        <div class="search_nav__navs">
                            {% for pag in next.paginator.page_range %}
                                {% if pag == next.number %}
                                    <div class="search_nav__nav">{{ pag }}</div>
                                {% else %}
                                    <a href="?next={{ pag }}"><div class="search_nav__nav">{{ pag }}</div></a>
                                {% endif %}
                            {% endfor %}
                        </div>
                        {% if next.has_next %}
                        <a href="?next={{ next.next_page_number }}"><div class="search_nav__next">далее →</div></a>
                        {% endif %}
                    </div>
                {% endif %}
                </div>
                <div class="match_list map__condition" data-id="2">
                {% for m in prev %}
                    {% include "_match-item-matches_lte.html" %}
                {% endfor %}
                {% if prev.has_next or prev.has_previous %}
                    <div class="search_nav">
                        <div class="search_nav__help">{{ prev.start_index }}—{{ prev.end_index }}</div>
                        {% if prev.has_previous %}
                        <a href="?prev={{ prev.previous_page_number }}"><div class="search_nav__next">← назад</div></a>
                        {% endif %}
                        <div class="search_nav__navs">
                            {% for pag in prev.paginator.page_range %}
                                {% if pag == prev.number %}
                                    <div class="search_nav__nav">{{ pag }}</div>
                                {% else %}
                                    <a href="?prev={{ pag }}"><div class="search_nav__nav">{{ pag }}</div></a>
                                {% endif %}
                            {% endfor %}
                        </div>
                        {% if prev.has_next %}
                        <a href="?prev={{ prev.next_page_number }}"><div class="search_nav__next">далее →</div></a>
                        {% endif %}
                    </div>
                {% endif %}
                </div>
            </div>
            <article class="seo_text">
                {% if data.content %}
                    {{ data.content|safe }}
                {% else %}
                    {% if seo.content %}{{ seo_content|safe }}{% endif %}
                {% endif %}
            </article>
        </div>
    </div>
{% endif %}

{% endblock %}

templates/champs.html
{% extends "_base.html" %}
{% load i18n %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ data.name }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ data.name }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ data.name }}{% endif %}">
{% endblock %}

{% block container %}
<div class="seasons_page minimum">
    <div class="match__head"><span>{% trans "Чемпионаты" %}</span></div>
    <div class="wrapper">
        <div class="breadcrumbs">
            <a href="/">{% trans "Билеты на матчи" %}</a>
            <span>{% trans "Чемпионаты" %}</span>
        </div>
        <h1 class="match__h1">{% trans "Чемпионаты" %}</h1>
        <div class="seasons_page__wrp">
            {% for c in champs %}
                <a href="{% url 'engine:champ' c.alias %}" class="champ_item">
                    <img width="140px" src="{% if c.image %}{{ c.image.url }}{% endif %}">
                    <span>{% trans "Сезон" %} {{ c.football_years }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/error_404.html
{% extends "_base.html" %}
{% load i18n %}
{% block container %}
<div class="seasons_page minimum">
    <div class="match__head"><span>Страница не найдена...</span></div>
    <div class="wrapper">
        <div class="breadcrumbs">
            <a href="/">Билеты на матчи</a>
            <span> Ошибка 404</span>
        </div>
        <h1 class="match__h1">Ошибка 404</h1>
        <article class="content" style="font-size: 16px;">
            <a href="/">Вернуться на главную</a>
        </article>
    </div>
</div>
{% endblock %}

templates/get_missing_orders.html
[{% for m in missing_orders %}{"pk": {{ m.pk }}, "client_name": "{% if m.name %}{{ m.name }}{% else %}-{% endif %}", "client_phone": "{% if m.phone %}{{ m.phone }}{% else %}-{% endif %}", "client_email": "{% if m.email %}{{ m.email }}{% else %}Не указан{% endif %}", "pay_type": {{ m.paymethod }}, "custom_id" : "{{ m.custom_id_str }}", "site_name" : "{{ m.host.name }}", "tickets" : [{% for t in m.c_tickets.all %}{"event_name" : "{{ t.match.name }}", "event_place_name": "{{ t.match.stadium.name }}, {{ t.match.stadium.city.name }}", "event_time_datetime": "{{ t.match.datetime|date:'Y-m-d\TH:i'}}", "sector_name": "{{ t.sector }}", "ticket_source_name": "{{ t.source }}", "row" : "{{ t.row }}", "seat": "{{ t.seat }}", "sale": "{{ t.price|floatformat:"-2" }}", "count" : 1}{% if forloop.last %}{% else %},{% endif %}{% endfor %}]}{% if forloop.last %}{% else %},{% endif %}{% endfor %}]

templates/matches.html
{% extends "_base.html" %}
{% load i18n %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ data.name }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ data.name }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ data.name }}{% endif %}">
{% endblock %}

{% block container %}
<div class="matches_page minimum">
    <div class="match__head">
        <span>{% trans "Матчи" %}</span>
    </div>
    <div class="wrapper">
        <div class="breadcrumbs">
            <a href="/">{% trans "Главная" %}</a>
            <span>{% trans "Матчи" %}</span>
        </div>
        <div class="match_tabs" style="width: 40%; margin: 20px auto 0;">
            <div class="switch">
                <div data-id="1" class="switch__element active">
                    Будущие матчи
                </div>
                <div data-id="2" class="switch__element">
                    Прошедшие матчи
                </div>
            </div>
        </div>
        <div class="match_list map__condition active" data-id="1">
        {% if next %}
            {% for m in next %}
                {% include "_match-item-matches.html" %}
            {% endfor %}
        {% else %}
            <h2 style="font-size: 20px;">Матчей нет</h2>
        {% endif %}
        {% if next.has_next or next.has_previous %}
            <div class="search_nav">
                <div class="search_nav__help">{{ next.start_index }}—{{ next.end_index }}</div>
                {% if next.has_previous %}
                <a href="?next={{ next.previous_page_number }}"><div class="search_nav__next">← назад</div></a>
                {% endif %}
                <div class="search_nav__navs">
                    {% for pag in next.paginator.page_range %}
                        {% if pag == next.number %}
                            <div class="search_nav__nav">{{ pag }}</div>
                        {% else %}
                            <a href="?next={{ pag }}"><div class="search_nav__nav">{{ pag }}</div></a>
                        {% endif %}
                    {% endfor %}
                </div>
                {% if next.has_next %}
                <a href="?next={{ next.next_page_number }}"><div class="search_nav__next">далее →</div></a>
                {% endif %}
            </div>
        {% endif %}
        </div>
        <div class="match_list map__condition" data-id="2">
        {% if prev %}
        {% for m in prev %}
            {% include "_match-item-matches_lte.html" %}
        {% endfor %}
        {% else %}
            <h2 style="font-size: 20px;">Матчей нет</h2>
        {% endif %}
        {% if prev.has_next or prev.has_previous %}
            <div class="search_nav">
                <div class="search_nav__help">{{ prev.start_index }}—{{ prev.end_index }}</div>
                {% if prev.has_previous %}
                <a href="?prev={{ prev.previous_page_number }}"><div class="search_nav__next">← назад</div></a>
                {% endif %}
                <div class="search_nav__navs">
                    {% for pag in prev.paginator.page_range %}
                        {% if pag == prev.number %}
                            <div class="search_nav__nav">{{ pag }}</div>
                        {% else %}
                            <a href="?prev={{ pag }}"><div class="search_nav__nav">{{ pag }}</div></a>
                        {% endif %}
                    {% endfor %}
                </div>
                {% if prev.has_next %}
                <a href="?prev={{ prev.next_page_number }}"><div class="search_nav__next">далее →</div></a>
                {% endif %}
            </div>
        {% endif %}
        </div>
        <article class="content seo_text">
            <h1>{{ data.seo_h1 }}</h1>
            {% if data.content %}
            {{ data.content|safe }}
            {% endif %}
            <table class="matches_for_index">
                <tbody>
                {% for m in upcoming_matches %}
                    {% ifchanged m.datetime.month %}
                    <tr>
                        <td class="matches_for_index_title" colspan="4">{% if sitesettings.main_champ.all %}Расписание хоккейных матчей{% else %}Билеты на матчи {{ sitesettings.main_team.name }}{% endif %} на {{ m.datetime|date:"F Y" }} года</td>
                    </tr>
                    <tr>
                        <th>Дата</th>
                        <th>Матч</th>
                        <th>Город</th>
                        <th>Наличие билетов</th>
                    </tr>
                    {% endifchanged %}
                    <tr>
                        <td>{{ m.datetime|date:"d.m.Y" }}</td>
                        <td><a href="{% url 'engine:match' m.static_match.alias m.alias %}">{{ m.command_first.name }} - {{ m.command_second.name }}</a></td>
                        <td>{{ m.stadium.city.name }}</td>
                        <td>{% if m.carryall_id or m.static_tickets.all|length %}{% trans "Доступно" %}{% else %}{% trans "Не доступно" %}{% endif %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </article>
    </div>
</div>
{% endblock %}
{% comment %}<a href="{% url 'engine:match_preview' m.static_match.alias %}" class="matches_page__match">{% if m.command_first.logo %}<img width="35px" src="https://footballengine.tix-system.com/media/teams/{{ m.command_first.logo }}">{% endif %}<span>{{ m.command_first.name }} - {{ m.command_second.name }}</span>{% if m.command_second.logo %}<img width="35px" src="https://footballengine.tix-system.com/media/teams/{{ m.command_second.logo }}">{% endif %}</a>{% endcomment %}

templates/matches_preview.html
{% extends "_base.html" %}
{% load i18n %}
{% block seo_titles %}
    <title>{% if data.seo_title %}{{ data.seo_title }}{% else %}{{ seo_title.static }}{% endif %}</title>
    <meta name="description" content="{% if data.seo_description %}{{ data.seo_description }}{% else %}{{ seo_description.static }}{% endif %}">
    <meta name="keywords" content="{% if data.seo_keywords %}{{ data.seo_keywords }}{% else %}{{ seo_keywords.static }}{% endif %}">
{% endblock %}

{% block container %}
<div class="matches_page minimum">
    <div class="match__head">
        <div class="mathc__w">
        {% if data.command_first.logo %}<a href='{% url "main:team" data.command_first.alias %}'><img width="100px" src="https://footballengine.tix-system.com/media/teams/{{ data.command_first.logo }}"></a>{% endif %}
        {{ data.command_first.name }} - {{ data.command_second.name }}
        {% if data.command_second.logo %}<a href='{% url "main:team" data.command_second.alias %}'><img width="100px" src="https://footballengine.tix-system.com/media/teams/{{ data.command_second.logo }}"></a>{% endif %}
        </div>
    </div>
    <div class="wrapper">
        <div class="breadcrumbs">
            <a href="/">{% trans "Билеты на матчи" %}</a>
            <span>{{ data.command_first.name }} - {{ data.command_second.name }}</span>
        </div>
        <h1 class="match__h1">{% if data.seo_h1 %}{{ data.seo_h1 }}{% else %}{{ seo_h1.static }}{% endif %}</h1>
        {% if matches_gte %}<div class="championat__wrp"><h2 class="match__h1">Следующие матчи</h2></div>{% endif %}
        <div class="championat">
            <div class="championat__wrp">
                {% for m in matches_gte %}
                    {% include "_match-item-matches2.html" %}
                {% endfor %}
            </div>
        <article class="seo_text">
            {% if data.content %}{{ data.content|safe }}{% else %}{{ seo_content|safe }}{% endif %}
        </article>
        <div class="championat">
            {% if matches_lte %}<div class="championat__wrp"><h2 class="match__h1">Прошедшие матчи</h2></div>{% endif %}
            {% for m in matches_lte %}
                {% include "_match-item-matches_lte.html" %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}